apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  volumes:
    - name: raycol-empty-vol
      emptyDir: {}
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 80
    volumeMounts:
      - name: raycol-empty-vol
        mountPath: /data
