apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raycoy
provisioner: kubernetes.io/aws-ebs # ebs.csi.aws.com
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-mongo-pvc
spec:
  storageClassName: raycoy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi