apiVersion: v1
kind: Pod
metadata:
  name: init-app
spec:
  initContainers:
  - name: init-service
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup melonservice; do echo waiting; sleep 2; done;']
  - name: init-db
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup melondb; do echo waiting on db; sleep 2; done;']
  containers:
  - name: main
    image: busybox:latest
    command: ['sh', '-c', 'echo The melonapp is running! && sleep 3600']