apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: first-deploy
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: first-deploy
  targetCPUUtilizationPercentage: 50