apiVersion: v1
kind: Pod
metadata:
  labels:
    app: chi-pod-cm
  name: chi-pod-cm
spec:
  containers:
  - image: nginx
    name: chi-pod-cm
    resources:
      requests:
        cpu: "0.5"
        memory: "5Gi"
      limits:
        cpu: "1.0"
        memory: "5Gi"
    envFrom:
      - configMapRef:
          name: chi-config