apiVersion: v1
kind: Pod
metadata:
  name: memcached
spec:
  containers:
  - name: memcached
    image: memcached:1.6.8
    envFrom:
      - configMapRef:
          name: db-config
      - configMapRef:
          name: testconfig
      - secretRef:
          name: secret-name
    # env: 
    #   - name: DB_URL
    #     valueFrom:
    #       configMapKeyRef:
    #         name: db-config2
    #         key: database_url