apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secrets
spec:
  volumes:
    - name: secret-vol
      secret:
        name: creds
  containers:
  - name: secret-pod
    image: nginx:alpine
    volumeMounts:
      - name: secret-vol
        mountPath: /etc/config