apiVersion: v1
kind: Pod
metadata:
  name: pod-with-label1
  labels:
    version: v0.1
    env: testing
    team: finance
  annotations:
    commit-SHA: d6s9shb82365yg4ygd782889us28377gf6
    JIRA-issue: "https://your-jira-link.com/issue/ABC-1234"
    owner: "https://internal-link.to.website/username"
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 80