# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: "/mnt/somenew/directory/structure/"
    type: DirectoryOrCreate

